apiVersion: v1
kind: Pod
metadata:
  name: api-gateway
spec:
	initContainers:
    - name: service-discovery
      image: service-discovery
	containers:
		-name: api-gateway
     image: api-gateway 
     ports:
     	- containerPort: 8080
     env:
	    - name: EUREKA_SERVER
	    value: service-discovery