apiVersion: v1
kind: Service
metadata:
	name: auth-service
spec:
	initContainers:
    - name: service-discovery
      image: service-discovery
	containers:
	- name: auth-service
    image: auth-service
	  ports: 
	  - containerPort: 9000
