apiVersion: v1
kind: Pod
metadata: 
  name: mysql-users-db
spec:
  containers:
    - name: mysql-users-db
      image: mysql:5.7
      ports:
      - containerPort: 3306
      volumeMounts:
      - name: users-db-volume
        mountPath: /var/lib/mysql
      env:
      - name: MYSQL_DATABASE
        value: users
      - name: MYSQL_TCP_PORT
        value: 3306  
#command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
  