apiVersion: v1
kind: Deployment
metadata: 
  name: mysql-courses-db
spec:
  selector:
    matchLabels: mysql-courses-db
  replicas: 1
  template:
    - name: mysql-courses-db
          image: mysql:5.7
      ports: 
        -  containerPort: 3307
        env:
            - name: MYSQL_DATABASE
              value: courses
      - name: MYSQL_TCP_PORT
              value: 3307
      command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
        volumeMounts:
        - mountPath: /var/lib/mysql
        name: courses-db-volume
     
        - name: service-discovery
          image: service-discovery
          ports:
            - containerPort: 8761