apiVersion: v1
kind: Service
metadata: 
  name: users-service
spec:
	initContainers:
		- name: mysql-users-db
      image: mysql:5.7
    - name: service-discovery
      image: service-discovery
  containers:          
  	- name: users-service
      image: users-service
		  ports:
		    - containerPort: 9001